# Generated by Django 6.0.2 on 2026-02-26 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diplome_disponibilite_vueprofil_evaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vueprofil',
            options={'verbose_name': 'Vue de profil', 'verbose_name_plural': 'Vues de profil'},
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='statistiques_de_vues',
        ),
        migrations.RemoveField(
            model_name='vueprofil',
            name='total_vues',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nb_vues_jour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nb_vues_mois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nb_vues_semaine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vueprofil',
            name='date_consultation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vueprofil',
            name='professeur_vise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='vueprofil',
            name='visiteur_id_technique',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vueprofil',
            name='visiteur_utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vues_profils', to=settings.AUTH_USER_MODEL),
        ),
    ]
