# Generated by Django 6.0.2 on 2026-02-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('numero_whatsapp', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('quartier_ville', models.CharField(blank=True, max_length=150)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='parents/photos/')),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_verifie', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='core.parent')),
            ],
        ),
    ]
