# Generated by Django 6.0.2 on 2026-02-26 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parent_enfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('objectifs', models.TextField()),
                ('difficultes_presentes', models.BooleanField()),
                ('difficultes_rencontrees', models.TextField(blank=True)),
                ('taches_domicile', models.TextField(blank=True)),
                ('total_points_obtenus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_points_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('taux_maitrise_seance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mois_index', models.DateField(blank=True, help_text='Premier jour du mois (pour filtrage)', null=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('validee', models.BooleanField(default=False)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.engagement')),
            ],
        ),
        migrations.CreateModel(
            name='NotionSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_notion', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField(help_text='Score de 0 à 3', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notions', to='core.seance')),
            ],
        ),
    ]
