# Generated by Django 6.0.2 on 2026-02-27 09:24

import core.choices
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seance_notionseance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='annulation_confirmee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='annulation_initiee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulations_initiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='budget_convenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='classe',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat')], max_length=30),
        ),
        migrations.AddField(
            model_name='engagement',
            name='cloture_confirmee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='cloture_initiee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_initiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_finalisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_heure_essai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='date_refus',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='duree_seance',
            field=models.CharField(blank=True, choices=[('1H', '1h'), ('1H30', '1h30'), ('2H', '2h'), ('2H30', '2h30'), ('3H', '3h')], max_length=10),
        ),
        migrations.AddField(
            model_name='engagement',
            name='enfants_concernes',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='core.enfant'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='evaluation_liee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='core.evaluation'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='frequence_hebdomadaire',
            field=models.CharField(blank=True, choices=[('1', '1 séance/semaine'), ('2', '2 séances/semaine'), ('3', '3 séances/semaine'), ('4', '4 séances/semaine'), ('5', '5 séances/semaine')], max_length=5),
        ),
        migrations.AddField(
            model_name='engagement',
            name='lien_cours_essai',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='engagement',
            name='localisation_option',
            field=models.CharField(blank=True, help_text='Format « Quartier-Ville »', max_length=150),
        ),
        migrations.AddField(
            model_name='engagement',
            name='masque_pour_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='masque_pour_professeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='matiere',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='engagement',
            name='mode_de_cours',
            field=models.CharField(blank=True, choices=[('PARENT_HOME', 'Présentiel chez le parent'), ('APPRENANT_HOME', "Présentiel chez l'apprenant"), ('ONLINE', 'En ligne'), ('HYBRID', 'Hybride (presentiel + en ligne par visioconférence)')], max_length=30),
        ),
        migrations.AddField(
            model_name='engagement',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='parent_apprenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='periode_engagement',
            field=models.CharField(blank=True, choices=[('1_MOIS', '1 mois'), ('3_MOIS', '3 mois'), ('6_MOIS', '6 mois'), ('1_AN', '1 an'), ('PONCTUEL', 'Ponctuel')], max_length=20),
        ),
        migrations.AddField(
            model_name='engagement',
            name='plateforme_visio_preferee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='engagement',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='statut_essai',
            field=models.CharField(blank=True, choices=[('PROGRAMME', 'Programmé'), ('CONFIRME', 'Confirmé'), ('COMPLETE', 'Complété')], max_length=20),
        ),
        migrations.AddField(
            model_name='engagement',
            name='statut_general',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('EN_COURS', 'En cours'), ('FINALISE', 'Finalisé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='engagement',
            name='taux_global_matiere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='temps_reponse_prof',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temps (en minutes) mis par le prof pour confirmer', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='total_points_max_matiere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='total_points_obtenus_matiere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='type_engagement',
            field=models.CharField(choices=[('ESSAI', 'Essai'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='engagement',
            name='vu_par_professeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='level',
            field=models.CharField(choices=[('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='classe',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='classes_enseignees',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes ClassLevel (ex: ['6EME','5EME'])", validators=[core.choices.validate_classes_enseignees]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='modes_de_cours',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes CourseMode (ex: ['ONLINE','HYBRID'])", validators=[core.choices.validate_modes_cours]),
        ),
    ]
