# Generated by Django 6.0.2 on 2026-02-27 09:32

import core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_engagement_annulation_confirmee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfant',
            old_name='nom',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='age',
        ),
        migrations.AddField(
            model_name='enfant',
            name='besoin_prioritaire',
            field=models.CharField(blank=True, choices=[('REMISE_NIVEAU', 'Remise à niveau'), ('PERFECTIONNEMENT', 'Perfectionnement'), ('PREPARATION_EXAMENS', 'Préparation aux examens'), ('SOUTIEN_REGULIER', 'Soutien régulier'), ('METHODO', 'Méthodologie et organisation')], max_length=20),
        ),
        migrations.AddField(
            model_name='enfant',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='etablissement_scolaire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enfant',
            name='matieres',
            field=models.JSONField(blank=True, default=list, help_text='Matières nécessitant un accompagnement (max 5)', validators=[core.choices.validate_matieres_max_5]),
        ),
        migrations.AddField(
            model_name='enfant',
            name='mode_de_cours',
            field=models.CharField(blank=True, choices=[('PARENT_HOME', 'Présentiel chez le parent'), ('APPRENANT_HOME', "Présentiel chez l'apprenant"), ('ONLINE', 'En ligne'), ('HYBRID', 'Hybride (presentiel + en ligne par visioconférence)')], max_length=30),
        ),
        migrations.AddField(
            model_name='enfant',
            name='niveau_percu',
            field=models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('BON_IRREGULIER', 'Bon mais irrégulier'), ('EXCELLENT', 'Excellent')], max_length=20),
        ),
        migrations.AddField(
            model_name='enfant',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('SUPERIEUR', 'Supérieur'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='enfant',
            name='objectif_principal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='quartier_ville',
            field=models.CharField(blank=True, help_text='Format « Quartier-Ville » pour matching avec professeurs', max_length=150),
        ),
        migrations.AddField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=5),
        ),
    ]
