# Generated by Django 6.0.2 on 2026-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_enfant_niveau_scolaire_abonnement_apprenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='prix',
            field=models.CharField(default='2000f par engagement', max_length=100),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ACCESS_PREMIUM', 'Access+Premium')], default='STANDARD', max_length=30),
        ),
    ]
