# Generated by Django 6.0.2 on 2026-02-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_abonnement_prix_alter_abonnement_type_abonnement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
