# Generated by Django 6.0.2 on 2026-04-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplome',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='diplome',
            name='intitule',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='liste_diplomes',
        ),
        migrations.AddField(
            model_name='diplome',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diplome',
            name='fichier_preuve',
            field=models.FileField(blank=True, null=True, upload_to='diplomes/'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='nom_diplome',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='diplome',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='grille_disponibilites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='message_admin',
            field=models.TextField(blank=True),
        ),
    ]
