# Generated by Django 6.0.4 on 2026-04-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_diplome_fichier_remove_diplome_intitule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.conversation'),
        ),
    ]
