# Generated by Django 6.0.4 on 2026-04-20 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_teacherprofile_slug_alter_engagement_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='nb_vues_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='parents_favoris',
            field=models.ManyToManyField(blank=True, help_text='Liste des parents marqués comme favoris par ce professeur', related_name='professeurs_favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
