# Generated by Django 6.0.4 on 2026-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_teacherprofile_nb_vues_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='statut_general',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'En cours'), ('EN_COURS', 'En cours'), ('FINALISE', 'Finalisé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
