# Generated by Django 6.0.4 on 2026-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_engagement_statut_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='statut_conversation',
            field=models.CharField(choices=[('DISCUSSION_LIBRE', 'Discussion libre'), ('NEGOCIATION', 'Engagement en négociation'), ('CONFIRME', 'Engagement en cours'), ('TERMINE', 'Engagement terminé'), ('CLOSE', 'Conversation close')], default='DISCUSSION_LIBRE', max_length=30),
        ),
    ]
