# Generated by Django 6.0.4 on 2026-04-27 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_conversation_statut_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='masque_par_parent',
            field=models.BooleanField(default=False, help_text="Si vrai, l'engagement n'est plus visible dans l'espace parent."),
        ),
        migrations.AddField(
            model_name='engagement',
            name='tarif_horaire_propose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),

        migrations.AlterField(
            model_name='engagement',
            name='statut_essai',
            field=models.CharField(blank=True, choices=[('PROGRAMME', 'Programmé'), ('CONFIRME', 'Confirmé'), ('COMPLETE', 'Complété')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu_texte',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(1, message='Le message ne peut pas être vide')]),
        ),
    ]
