# Generated by Django 6.0.2 on 2026-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_engagement_masque_par_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='temps_moyen_reponse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Temps de réponse moyen en minutes', max_digits=10),
        ),
    ]
