# Generated by Django 6.0.4 on 2026-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_teacherprofile_temps_moyen_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='date_heure_fin_essai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='description_essai',
            field=models.TextField(blank=True),
        ),
    ]
