# Generated by Django 6.0.4 on 2026-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_engagement_date_heure_fin_essai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='note_initiale_equipe',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text="Note attribuée par l'équipe à la validation", max_digits=3),
        ),
    ]
