# Generated by Django 6.0.4 on 2026-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_teacherprofile_note_initiale_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='duree_mois',
            field=models.IntegerField(blank=True, help_text='Durée souhaitée en mois', null=True),
        ),
    ]
