# Generated by Django 6.0.4 on 2026-05-07 00:02

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_apprenant_preference_de_cours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archivee_par',
            field=models.ManyToManyField(blank=True, related_name='conversations_archivees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='masquee_par',
            field=models.ManyToManyField(blank=True, related_name='conversations_masquees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='prix',
            field=models.CharField(default=core.models.get_default_abonnement_price, max_length=100),
        ),
    ]
