# Generated by Django 6.0.4 on 2026-05-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_conversation_archivee_par_conversation_masquee_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profil_complet',
            field=models.BooleanField(default=False, help_text='Vrai si le profil est complété à 100%'),
        ),
    ]
