# Generated by Django 6.0.4 on 2026-05-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_teacherprofile_profil_complet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='categorie_de_soutien',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='categories_de_soutien',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes SupportCategory'),
        ),
    ]
