# Generated by Django 6.0.4 on 2026-05-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_teacherprofile_categorie_de_soutien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='a_vu_popup_bienvenue',
            field=models.BooleanField(default=False, help_text='Détermine si le popup de bienvenue (Apprenant/Parent) a déjà été fermé.'),
        ),
    ]
