# Generated by Django 6.0.4 on 2026-05-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_professorannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFedaPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text="L'ID de transaction généré par FedaPay", max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, default=2000.0, help_text='Montant en FCFA', max_digits=8)),
                ('statut', models.CharField(default='pending', help_text='Statut renvoyé par FedaPay (ex: pending, approved, declined)', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('engagement', models.ForeignKey(help_text="L'engagement lié à ce paiement", on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.engagement')),
            ],
        ),
    ]
