# Generated by Django 6.0.4 on 2026-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_teacherprofile_nombre_apparitions_recherche'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='nombre_apparitions_mois',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
