# Generated by Django 6.0.4 on 2026-05-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_teacherprofile_nombre_apparitions_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorannouncement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Tous les utilisateurs'), ('PROF', 'Professeurs uniquement'), ('PARENT_APPRENANT', 'Parents et Apprenants uniquement')], default='ALL', max_length=20),
        ),
    ]
