# Generated by Django 6.0.2 on 2026-05-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_professorannouncement_target_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfedapay',
            name='type_transaction',
            field=models.CharField(choices=[('ENGAGEMENT', 'Engagement'), ('ABONNEMENT', 'Abonnement')], default='ENGAGEMENT', help_text='Type de la transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionfedapay',
            name='user',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur qui effectue le paiement (requis pour les abonnements)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_fedapay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionfedapay',
            name='engagement',
            field=models.ForeignKey(blank=True, help_text="L'engagement lié à ce paiement (pour type ENGAGEMENT)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.engagement'),
        ),
    ]
