# Generated by Django 6.0.4 on 2026-05-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_transactionfedapay_type_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='indications_geographiques',
            field=models.TextField(blank=True, help_text='Indications pour trouver la maison (pour les cours à domicile)'),
        ),
    ]
