# Generated by Django 6.0.4 on 2026-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_indications_geographiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='statut_general',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente (Ancien)'), ('CONFIRME', 'En cours (Ancien)'), ('EN_COURS', 'En cours (Ancien)'), ('FINALISE', 'Finalisé (Ancien)'), ('ESSAI_PROGRAMME', 'Essai programmé'), ('ESSAI_CONFIRME', 'Essai confirmé'), ('ESSAI_REALISE', 'Essai réalisé'), ('ENGAGEMENT_FINALISE', 'Engagement finalisé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='ESSAI_PROGRAMME', max_length=20),
        ),
    ]
