# Generated by Django 6.0.4 on 2026-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_profile_telephone_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nb_profils_consultes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='nb_recherches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nb_vues_profil',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
