# Generated by Django 6.0.4 on 2026-06-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_parent_nb_profils_consultes_parent_nb_recherches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='nb_profils_consultes',
            field=models.IntegerField(default=0, help_text='Nombre de profils professeurs consultés'),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='nb_recherches',
            field=models.IntegerField(default=0, help_text='Nombre de recherches effectuées'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nb_connexions',
            field=models.IntegerField(default=0, help_text="Récurrence d'utilisation"),
        ),
        migrations.AddField(
            model_name='profile',
            name='nb_vues_page_plan',
            field=models.IntegerField(default=0, help_text="Intention d'achat : Vues de la page Gérer mon plan"),
        ),
        migrations.AddField(
            model_name='profile',
            name='nb_vues_suivi',
            field=models.IntegerField(default=0, help_text='Intérêt suivi : Vues de la page de suivi pédagogique'),
        ),
    ]
