# Generated by Django 6.0.4 on 2026-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_apprenant_nb_profils_consultes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='video_presentation',
            field=models.URLField(blank=True, help_text='Lien YouTube ou TikTok de présentation', null=True),
        ),
    ]
