# Generated by Django 6.0.4 on 2026-06-12 07:33

import core.choices
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_teacherprofile_video_presentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Professeur',
                'verbose_name_plural': 'FAQs Professeurs',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='RessourceProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(upload_to='ressources_profs/')),
                ('est_guide_officiel', models.BooleanField(default=False, help_text='Cochez ceci si ce document est le Guide Officiel téléchargeable depuis le bouton principal.')),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ressource Professeur',
                'verbose_name_plural': 'Ressources Professeurs',
                'ordering': ['ordre_affichage', '-date_creation'],
            },
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'Ã‰valuation', 'verbose_name_plural': 'Ã‰valuations'},
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='matieres_recherchees',
            field=models.JSONField(blank=True, default=list, help_text='MatiÃ¨res prioritaires (max 5)', validators=[core.choices.validate_matieres_recherchees_max_5]),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='nb_profils_consultes',
            field=models.IntegerField(default=0, help_text='Nombre de profils professeurs consultÃ©s'),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='nb_recherches',
            field=models.IntegerField(default=0, help_text='Nombre de recherches effectuÃ©es'),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='nom',
            field=models.CharField(help_text='Nom et prÃ©nom', max_length=200),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='quartier_ville',
            field=models.CharField(blank=True, choices=[('Abokicodji - Cotonou', 'Abokicodji - Cotonou'), ('Adidogomé - Abomey-Calavi', 'Adidogomé - Abomey-Calavi'), ('Adjagbo - Abomey-Calavi', 'Adjagbo - Abomey-Calavi'), ('Adjamé - Cotonou', 'Adjamé - Cotonou'), ('Adjégounlè - Porto-Novo', 'Adjégounlè - Porto-Novo'), ('Adogéta - Porto-Novo', 'Adogéta - Porto-Novo'), ('Agblangandan - Sèmè-Kpodji', 'Agblangandan - Sèmè-Kpodji'), ('Agla - Cotonou', 'Agla - Cotonou'), ('Agontikon - Cotonou', 'Agontikon - Cotonou'), ('Agori - Abomey-Calavi', 'Agori - Abomey-Calavi'), ('Agouako - Abomey-Calavi', 'Agouako - Abomey-Calavi'), ('Ahogbohouè - Cotonou', 'Ahogbohouè - Cotonou'), ('Aidjèdo - Cotonou', 'Aidjèdo - Cotonou'), ('Akassato - Abomey-Calavi', 'Akassato - Abomey-Calavi'), ('Akpakpa - Cotonou', 'Akpakpa - Cotonou'), ('Akron - Porto-Novo', 'Akron - Porto-Novo'), ('Alaga - Parakou', 'Alaga - Parakou'), ('Albarika - Parakou', 'Albarika - Parakou'), ('Amanwignon - Parakou', 'Amanwignon - Parakou'), ('Atchakpa - Porto-Novo', 'Atchakpa - Porto-Novo'), ('Atrokpocodji - Abomey-Calavi', 'Atrokpocodji - Abomey-Calavi'), ('Avakpa - Porto-Novo', 'Avakpa - Porto-Novo'), ('Avotrou - Cotonou', 'Avotrou - Cotonou'), ('Awansouri - Cotonou', 'Awansouri - Cotonou'), ('Ayélawadjè - Cotonou', 'Ayélawadjè - Cotonou'), ('Bakinkoura - Parakou', 'Bakinkoura - Parakou'), ('Banikanni - Parakou', 'Banikanni - Parakou'), ('Bidossessi - Abomey-Calavi', 'Bidossessi - Abomey-Calavi'), ('Cadjèhoun - Cotonou', 'Cadjèhoun - Cotonou'), ('Camp Adagbé - Porto-Novo', 'Camp Adagbé - Porto-Novo'), ('Cocotomey - Abomey-Calavi', 'Cocotomey - Abomey-Calavi'), ('Dandji - Cotonou', 'Dandji - Cotonou'), ('Davatin - Porto-Novo', 'Davatin - Porto-Novo'), ('Dépôt - Parakou', 'Dépôt - Parakou'), ('Djassin - Porto-Novo', 'Djassin - Porto-Novo'), ('Djidjè - Cotonou', 'Djidjè - Cotonou'), ('Djifa-Prix - Cotonou', 'Djifa-Prix - Cotonou'), ('Djougou-Kpota - Djougou', 'Djougou-Kpota - Djougou'), ('Dokparou - Parakou', 'Dokparou - Parakou'), ('Donaten - Cotonou', 'Donaten - Cotonou'), ('Dowa - Porto-Novo', 'Dowa - Porto-Novo'), ('Enagnon - Cotonou', 'Enagnon - Cotonou'), ('Fidjrossè - Cotonou', 'Fidjrossè - Cotonou'), ('Fonkpame - Porto-Novo', 'Fonkpame - Porto-Novo'), ('Ganhoto - Porto-Novo', 'Ganhoto - Porto-Novo'), ('Ganhi - Cotonou', 'Ganhi - Cotonou'), ('Gbèdjromèdé - Cotonou', 'Gbèdjromèdé - Cotonou'), ('Gbégamey - Cotonou', 'Gbégamey - Cotonou'), ('Gbégnigan - Cotonou', 'Gbégnigan - Cotonou'), ('Gbodjé - Abomey-Calavi', 'Gbodjé - Abomey-Calavi'), ('Glo-Djigbé - Abomey-Calavi', 'Glo-Djigbé - Abomey-Calavi'), ('Godomey - Abomey-Calavi', 'Godomey - Abomey-Calavi'), ('Gorobani - Parakou', 'Gorobani - Parakou'), ('Guéma - Parakou', 'Guéma - Parakou'), ('Haie Vive - Cotonou', 'Haie Vive - Cotonou'), ('Hindé - Cotonou', 'Hindé - Cotonou'), ('Hogbonou - Porto-Novo', 'Hogbonou - Porto-Novo'), ('Houéyiho - Cotonou', 'Houéyiho - Cotonou'), ('Houézoumè - Cotonou', 'Houézoumè - Cotonou'), ('Houinmè - Porto-Novo', 'Houinmè - Porto-Novo'), ('Hounsa - Porto-Novo', 'Hounsa - Porto-Novo'), ('Jéricho - Cotonou', 'Jéricho - Cotonou'), ('Kadébou - Parakou', 'Kadébou - Parakou'), ('Kindonou - Cotonou', 'Kindonou - Cotonou'), ('Komè - Porto-Novo', 'Komè - Porto-Novo'), ('Kouhounou - Cotonou', 'Kouhounou - Cotonou'), ('Kpébié - Parakou', 'Kpébié - Parakou'), ('Kpékpédji - Abomey-Calavi', 'Kpékpédji - Abomey-Calavi'), ('Kpondehou - Cotonou', 'Kpondehou - Cotonou'), ('Ladji - Cotonou', 'Ladji - Cotonou'), ('Ladjifarani - Parakou', 'Ladjifarani - Parakou'), ('Les Cocotiers - Cotonou', 'Les Cocotiers - Cotonou'), ('Lobozounkpa - Abomey-Calavi', 'Lobozounkpa - Abomey-Calavi'), ('Madina - Parakou', 'Madina - Parakou'), ('Maria-Gléta - Abomey-Calavi', 'Maria-Gléta - Abomey-Calavi'), ('Maro-Militaire - Cotonou', 'Maro-Militaire - Cotonou'), ('Menontin - Cotonou', 'Menontin - Cotonou'), ('Missébo - Cotonou', 'Missébo - Cotonou'), ('Missessin - Cotonou', 'Missessin - Cotonou'), ('Missité - Cotonou', 'Missité - Cotonou'), ('Moumouni - Parakou', 'Moumouni - Parakou'), ('Nato - Cotonou', 'Nato - Cotonou'), ('Okpè-Oyouré - Porto-Novo', 'Okpè-Oyouré - Porto-Novo'), ('Ouando - Porto-Novo', 'Ouando - Porto-Novo'), ('Ouinmeko - Porto-Novo', 'Ouinmeko - Porto-Novo'), ('Padonou - Abomey-Calavi', 'Padonou - Abomey-Calavi'), ('Parana - Parakou', 'Parana - Parakou'), ('Placodji - Cotonou', 'Placodji - Cotonou'), ('Saint Hubert - Cotonou', 'Saint Hubert - Cotonou'), ('Sainte Rita - Cotonou', 'Sainte Rita - Cotonou'), ('Segbeya - Cotonou', 'Segbeya - Cotonou'), ('Sodohomè - Bohicon', 'Sodohomè - Bohicon'), ('Somankpon - Abomey-Calavi', 'Somankpon - Abomey-Calavi'), ('Tankpè - Abomey-Calavi', 'Tankpè - Abomey-Calavi'), ('Titirou - Parakou', 'Titirou - Parakou'), ('Togoudo - Abomey-Calavi', 'Togoudo - Abomey-Calavi'), ('Tokpa-Hoho - Cotonou', 'Tokpa-Hoho - Cotonou'), ('Vedoko - Cotonou', 'Vedoko - Cotonou'), ('Wonkoro - Parakou', 'Wonkoro - Parakou'), ('Zogbo - Cotonou', 'Zogbo - Cotonou')], help_text='Format Â« Quartier - Ville Â» pour matching', max_length=150),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='telephone',
            field=models.CharField(blank=True, help_text='NumÃ©ro WhatsApp', max_length=50),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='matieres',
            field=models.JSONField(blank=True, default=list, help_text='MatiÃ¨res nÃ©cessitant un accompagnement (max 5)', validators=[core.choices.validate_matieres_max_5]),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='quartier_ville',
            field=models.CharField(blank=True, choices=[('Abokicodji - Cotonou', 'Abokicodji - Cotonou'), ('Adidogomé - Abomey-Calavi', 'Adidogomé - Abomey-Calavi'), ('Adjagbo - Abomey-Calavi', 'Adjagbo - Abomey-Calavi'), ('Adjamé - Cotonou', 'Adjamé - Cotonou'), ('Adjégounlè - Porto-Novo', 'Adjégounlè - Porto-Novo'), ('Adogéta - Porto-Novo', 'Adogéta - Porto-Novo'), ('Agblangandan - Sèmè-Kpodji', 'Agblangandan - Sèmè-Kpodji'), ('Agla - Cotonou', 'Agla - Cotonou'), ('Agontikon - Cotonou', 'Agontikon - Cotonou'), ('Agori - Abomey-Calavi', 'Agori - Abomey-Calavi'), ('Agouako - Abomey-Calavi', 'Agouako - Abomey-Calavi'), ('Ahogbohouè - Cotonou', 'Ahogbohouè - Cotonou'), ('Aidjèdo - Cotonou', 'Aidjèdo - Cotonou'), ('Akassato - Abomey-Calavi', 'Akassato - Abomey-Calavi'), ('Akpakpa - Cotonou', 'Akpakpa - Cotonou'), ('Akron - Porto-Novo', 'Akron - Porto-Novo'), ('Alaga - Parakou', 'Alaga - Parakou'), ('Albarika - Parakou', 'Albarika - Parakou'), ('Amanwignon - Parakou', 'Amanwignon - Parakou'), ('Atchakpa - Porto-Novo', 'Atchakpa - Porto-Novo'), ('Atrokpocodji - Abomey-Calavi', 'Atrokpocodji - Abomey-Calavi'), ('Avakpa - Porto-Novo', 'Avakpa - Porto-Novo'), ('Avotrou - Cotonou', 'Avotrou - Cotonou'), ('Awansouri - Cotonou', 'Awansouri - Cotonou'), ('Ayélawadjè - Cotonou', 'Ayélawadjè - Cotonou'), ('Bakinkoura - Parakou', 'Bakinkoura - Parakou'), ('Banikanni - Parakou', 'Banikanni - Parakou'), ('Bidossessi - Abomey-Calavi', 'Bidossessi - Abomey-Calavi'), ('Cadjèhoun - Cotonou', 'Cadjèhoun - Cotonou'), ('Camp Adagbé - Porto-Novo', 'Camp Adagbé - Porto-Novo'), ('Cocotomey - Abomey-Calavi', 'Cocotomey - Abomey-Calavi'), ('Dandji - Cotonou', 'Dandji - Cotonou'), ('Davatin - Porto-Novo', 'Davatin - Porto-Novo'), ('Dépôt - Parakou', 'Dépôt - Parakou'), ('Djassin - Porto-Novo', 'Djassin - Porto-Novo'), ('Djidjè - Cotonou', 'Djidjè - Cotonou'), ('Djifa-Prix - Cotonou', 'Djifa-Prix - Cotonou'), ('Djougou-Kpota - Djougou', 'Djougou-Kpota - Djougou'), ('Dokparou - Parakou', 'Dokparou - Parakou'), ('Donaten - Cotonou', 'Donaten - Cotonou'), ('Dowa - Porto-Novo', 'Dowa - Porto-Novo'), ('Enagnon - Cotonou', 'Enagnon - Cotonou'), ('Fidjrossè - Cotonou', 'Fidjrossè - Cotonou'), ('Fonkpame - Porto-Novo', 'Fonkpame - Porto-Novo'), ('Ganhoto - Porto-Novo', 'Ganhoto - Porto-Novo'), ('Ganhi - Cotonou', 'Ganhi - Cotonou'), ('Gbèdjromèdé - Cotonou', 'Gbèdjromèdé - Cotonou'), ('Gbégamey - Cotonou', 'Gbégamey - Cotonou'), ('Gbégnigan - Cotonou', 'Gbégnigan - Cotonou'), ('Gbodjé - Abomey-Calavi', 'Gbodjé - Abomey-Calavi'), ('Glo-Djigbé - Abomey-Calavi', 'Glo-Djigbé - Abomey-Calavi'), ('Godomey - Abomey-Calavi', 'Godomey - Abomey-Calavi'), ('Gorobani - Parakou', 'Gorobani - Parakou'), ('Guéma - Parakou', 'Guéma - Parakou'), ('Haie Vive - Cotonou', 'Haie Vive - Cotonou'), ('Hindé - Cotonou', 'Hindé - Cotonou'), ('Hogbonou - Porto-Novo', 'Hogbonou - Porto-Novo'), ('Houéyiho - Cotonou', 'Houéyiho - Cotonou'), ('Houézoumè - Cotonou', 'Houézoumè - Cotonou'), ('Houinmè - Porto-Novo', 'Houinmè - Porto-Novo'), ('Hounsa - Porto-Novo', 'Hounsa - Porto-Novo'), ('Jéricho - Cotonou', 'Jéricho - Cotonou'), ('Kadébou - Parakou', 'Kadébou - Parakou'), ('Kindonou - Cotonou', 'Kindonou - Cotonou'), ('Komè - Porto-Novo', 'Komè - Porto-Novo'), ('Kouhounou - Cotonou', 'Kouhounou - Cotonou'), ('Kpébié - Parakou', 'Kpébié - Parakou'), ('Kpékpédji - Abomey-Calavi', 'Kpékpédji - Abomey-Calavi'), ('Kpondehou - Cotonou', 'Kpondehou - Cotonou'), ('Ladji - Cotonou', 'Ladji - Cotonou'), ('Ladjifarani - Parakou', 'Ladjifarani - Parakou'), ('Les Cocotiers - Cotonou', 'Les Cocotiers - Cotonou'), ('Lobozounkpa - Abomey-Calavi', 'Lobozounkpa - Abomey-Calavi'), ('Madina - Parakou', 'Madina - Parakou'), ('Maria-Gléta - Abomey-Calavi', 'Maria-Gléta - Abomey-Calavi'), ('Maro-Militaire - Cotonou', 'Maro-Militaire - Cotonou'), ('Menontin - Cotonou', 'Menontin - Cotonou'), ('Missébo - Cotonou', 'Missébo - Cotonou'), ('Missessin - Cotonou', 'Missessin - Cotonou'), ('Missité - Cotonou', 'Missité - Cotonou'), ('Moumouni - Parakou', 'Moumouni - Parakou'), ('Nato - Cotonou', 'Nato - Cotonou'), ('Okpè-Oyouré - Porto-Novo', 'Okpè-Oyouré - Porto-Novo'), ('Ouando - Porto-Novo', 'Ouando - Porto-Novo'), ('Ouinmeko - Porto-Novo', 'Ouinmeko - Porto-Novo'), ('Padonou - Abomey-Calavi', 'Padonou - Abomey-Calavi'), ('Parana - Parakou', 'Parana - Parakou'), ('Placodji - Cotonou', 'Placodji - Cotonou'), ('Saint Hubert - Cotonou', 'Saint Hubert - Cotonou'), ('Sainte Rita - Cotonou', 'Sainte Rita - Cotonou'), ('Segbeya - Cotonou', 'Segbeya - Cotonou'), ('Sodohomè - Bohicon', 'Sodohomè - Bohicon'), ('Somankpon - Abomey-Calavi', 'Somankpon - Abomey-Calavi'), ('Tankpè - Abomey-Calavi', 'Tankpè - Abomey-Calavi'), ('Titirou - Parakou', 'Titirou - Parakou'), ('Togoudo - Abomey-Calavi', 'Togoudo - Abomey-Calavi'), ('Tokpa-Hoho - Cotonou', 'Tokpa-Hoho - Cotonou'), ('Vedoko - Cotonou', 'Vedoko - Cotonou'), ('Wonkoro - Parakou', 'Wonkoro - Parakou'), ('Zogbo - Cotonou', 'Zogbo - Cotonou')], help_text='Format Â« Quartier - Ville Â» pour matching avec professeurs', max_length=150),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='duree_mois',
            field=models.IntegerField(blank=True, help_text='DurÃ©e souhaitÃ©e en mois', null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='indications_geographiques',
            field=models.TextField(blank=True, help_text='Indications pour trouver la maison (pour les cours Ã\xa0 domicile)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='localisation_option',
            field=models.CharField(blank=True, help_text='Format Â« Quartier-Ville Â»', max_length=150),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu_texte',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(1, message='Le message ne peut pas Ãªtre vide')]),
        ),
        migrations.AlterField(
            model_name='notionseance',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Score de 0 Ã\xa0 3', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='a_vu_popup_bienvenue',
            field=models.BooleanField(default=False, help_text='DÃ©termine si le popup de bienvenue (Apprenant/Parent) a dÃ©jÃ\xa0 Ã©tÃ© fermÃ©.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nb_connexions',
            field=models.IntegerField(default=0, help_text="RÃ©currence d'utilisation"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nb_vues_page_plan',
            field=models.IntegerField(default=0, help_text="Intention d'achat : Vues de la page GÃ©rer mon plan"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nb_vues_suivi',
            field=models.IntegerField(default=0, help_text='IntÃ©rÃªt suivi : Vues de la page de suivi pÃ©dagogique'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='note_initiale_equipe',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text="Note attribuÃ©e par l'Ã©quipe Ã\xa0 la validation", max_digits=3),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='parents_favoris',
            field=models.ManyToManyField(blank=True, help_text='Liste des parents marquÃ©s comme favoris par ce professeur', related_name='professeurs_favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profil_complet',
            field=models.BooleanField(default=False, help_text='Vrai si le profil est complÃ©tÃ© Ã\xa0 100%'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='temps_moyen_reponse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Temps de rÃ©ponse moyen en minutes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='video_presentation',
            field=models.URLField(blank=True, help_text='Lien YouTube ou TikTok de prÃ©sentation', null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ville_quartier',
            field=models.CharField(choices=[('Abokicodji - Cotonou', 'Abokicodji - Cotonou'), ('Adidogomé - Abomey-Calavi', 'Adidogomé - Abomey-Calavi'), ('Adjagbo - Abomey-Calavi', 'Adjagbo - Abomey-Calavi'), ('Adjamé - Cotonou', 'Adjamé - Cotonou'), ('Adjégounlè - Porto-Novo', 'Adjégounlè - Porto-Novo'), ('Adogéta - Porto-Novo', 'Adogéta - Porto-Novo'), ('Agblangandan - Sèmè-Kpodji', 'Agblangandan - Sèmè-Kpodji'), ('Agla - Cotonou', 'Agla - Cotonou'), ('Agontikon - Cotonou', 'Agontikon - Cotonou'), ('Agori - Abomey-Calavi', 'Agori - Abomey-Calavi'), ('Agouako - Abomey-Calavi', 'Agouako - Abomey-Calavi'), ('Ahogbohouè - Cotonou', 'Ahogbohouè - Cotonou'), ('Aidjèdo - Cotonou', 'Aidjèdo - Cotonou'), ('Akassato - Abomey-Calavi', 'Akassato - Abomey-Calavi'), ('Akpakpa - Cotonou', 'Akpakpa - Cotonou'), ('Akron - Porto-Novo', 'Akron - Porto-Novo'), ('Alaga - Parakou', 'Alaga - Parakou'), ('Albarika - Parakou', 'Albarika - Parakou'), ('Amanwignon - Parakou', 'Amanwignon - Parakou'), ('Atchakpa - Porto-Novo', 'Atchakpa - Porto-Novo'), ('Atrokpocodji - Abomey-Calavi', 'Atrokpocodji - Abomey-Calavi'), ('Avakpa - Porto-Novo', 'Avakpa - Porto-Novo'), ('Avotrou - Cotonou', 'Avotrou - Cotonou'), ('Awansouri - Cotonou', 'Awansouri - Cotonou'), ('Ayélawadjè - Cotonou', 'Ayélawadjè - Cotonou'), ('Bakinkoura - Parakou', 'Bakinkoura - Parakou'), ('Banikanni - Parakou', 'Banikanni - Parakou'), ('Bidossessi - Abomey-Calavi', 'Bidossessi - Abomey-Calavi'), ('Cadjèhoun - Cotonou', 'Cadjèhoun - Cotonou'), ('Camp Adagbé - Porto-Novo', 'Camp Adagbé - Porto-Novo'), ('Cocotomey - Abomey-Calavi', 'Cocotomey - Abomey-Calavi'), ('Dandji - Cotonou', 'Dandji - Cotonou'), ('Davatin - Porto-Novo', 'Davatin - Porto-Novo'), ('Dépôt - Parakou', 'Dépôt - Parakou'), ('Djassin - Porto-Novo', 'Djassin - Porto-Novo'), ('Djidjè - Cotonou', 'Djidjè - Cotonou'), ('Djifa-Prix - Cotonou', 'Djifa-Prix - Cotonou'), ('Djougou-Kpota - Djougou', 'Djougou-Kpota - Djougou'), ('Dokparou - Parakou', 'Dokparou - Parakou'), ('Donaten - Cotonou', 'Donaten - Cotonou'), ('Dowa - Porto-Novo', 'Dowa - Porto-Novo'), ('Enagnon - Cotonou', 'Enagnon - Cotonou'), ('Fidjrossè - Cotonou', 'Fidjrossè - Cotonou'), ('Fonkpame - Porto-Novo', 'Fonkpame - Porto-Novo'), ('Ganhoto - Porto-Novo', 'Ganhoto - Porto-Novo'), ('Ganhi - Cotonou', 'Ganhi - Cotonou'), ('Gbèdjromèdé - Cotonou', 'Gbèdjromèdé - Cotonou'), ('Gbégamey - Cotonou', 'Gbégamey - Cotonou'), ('Gbégnigan - Cotonou', 'Gbégnigan - Cotonou'), ('Gbodjé - Abomey-Calavi', 'Gbodjé - Abomey-Calavi'), ('Glo-Djigbé - Abomey-Calavi', 'Glo-Djigbé - Abomey-Calavi'), ('Godomey - Abomey-Calavi', 'Godomey - Abomey-Calavi'), ('Gorobani - Parakou', 'Gorobani - Parakou'), ('Guéma - Parakou', 'Guéma - Parakou'), ('Haie Vive - Cotonou', 'Haie Vive - Cotonou'), ('Hindé - Cotonou', 'Hindé - Cotonou'), ('Hogbonou - Porto-Novo', 'Hogbonou - Porto-Novo'), ('Houéyiho - Cotonou', 'Houéyiho - Cotonou'), ('Houézoumè - Cotonou', 'Houézoumè - Cotonou'), ('Houinmè - Porto-Novo', 'Houinmè - Porto-Novo'), ('Hounsa - Porto-Novo', 'Hounsa - Porto-Novo'), ('Jéricho - Cotonou', 'Jéricho - Cotonou'), ('Kadébou - Parakou', 'Kadébou - Parakou'), ('Kindonou - Cotonou', 'Kindonou - Cotonou'), ('Komè - Porto-Novo', 'Komè - Porto-Novo'), ('Kouhounou - Cotonou', 'Kouhounou - Cotonou'), ('Kpébié - Parakou', 'Kpébié - Parakou'), ('Kpékpédji - Abomey-Calavi', 'Kpékpédji - Abomey-Calavi'), ('Kpondehou - Cotonou', 'Kpondehou - Cotonou'), ('Ladji - Cotonou', 'Ladji - Cotonou'), ('Ladjifarani - Parakou', 'Ladjifarani - Parakou'), ('Les Cocotiers - Cotonou', 'Les Cocotiers - Cotonou'), ('Lobozounkpa - Abomey-Calavi', 'Lobozounkpa - Abomey-Calavi'), ('Madina - Parakou', 'Madina - Parakou'), ('Maria-Gléta - Abomey-Calavi', 'Maria-Gléta - Abomey-Calavi'), ('Maro-Militaire - Cotonou', 'Maro-Militaire - Cotonou'), ('Menontin - Cotonou', 'Menontin - Cotonou'), ('Missébo - Cotonou', 'Missébo - Cotonou'), ('Missessin - Cotonou', 'Missessin - Cotonou'), ('Missité - Cotonou', 'Missité - Cotonou'), ('Moumouni - Parakou', 'Moumouni - Parakou'), ('Nato - Cotonou', 'Nato - Cotonou'), ('Okpè-Oyouré - Porto-Novo', 'Okpè-Oyouré - Porto-Novo'), ('Ouando - Porto-Novo', 'Ouando - Porto-Novo'), ('Ouinmeko - Porto-Novo', 'Ouinmeko - Porto-Novo'), ('Padonou - Abomey-Calavi', 'Padonou - Abomey-Calavi'), ('Parana - Parakou', 'Parana - Parakou'), ('Placodji - Cotonou', 'Placodji - Cotonou'), ('Saint Hubert - Cotonou', 'Saint Hubert - Cotonou'), ('Sainte Rita - Cotonou', 'Sainte Rita - Cotonou'), ('Segbeya - Cotonou', 'Segbeya - Cotonou'), ('Sodohomè - Bohicon', 'Sodohomè - Bohicon'), ('Somankpon - Abomey-Calavi', 'Somankpon - Abomey-Calavi'), ('Tankpè - Abomey-Calavi', 'Tankpè - Abomey-Calavi'), ('Titirou - Parakou', 'Titirou - Parakou'), ('Togoudo - Abomey-Calavi', 'Togoudo - Abomey-Calavi'), ('Tokpa-Hoho - Cotonou', 'Tokpa-Hoho - Cotonou'), ('Vedoko - Cotonou', 'Vedoko - Cotonou'), ('Wonkoro - Parakou', 'Wonkoro - Parakou'), ('Zogbo - Cotonou', 'Zogbo - Cotonou')], help_text='Format Â« Quartier - Ville Â»', max_length=150),
        ),
        migrations.AlterField(
            model_name='transactionfedapay',
            name='engagement',
            field=models.ForeignKey(blank=True, help_text="L'engagement liÃ© Ã\xa0 ce paiement (pour type ENGAGEMENT)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.engagement'),
        ),
        migrations.AlterField(
            model_name='transactionfedapay',
            name='statut',
            field=models.CharField(default='pending', help_text='Statut renvoyÃ© par FedaPay (ex: pending, approved, declined)', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionfedapay',
            name='transaction_id',
            field=models.CharField(help_text="L'ID de transaction gÃ©nÃ©rÃ© par FedaPay", max_length=100, unique=True),
        ),
    ]
