# Generated by Django 6.0.4 on 2026-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_faqprofesseur_ressourceprofesseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourceprofesseur',
            name='lien_externe',
            field=models.URLField(blank=True, help_text='Lien Google Drive ou autre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ressourceprofesseur',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ressources_profs/'),
        ),
    ]
