# Generated by Django 6.0.4 on 2026-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_ressourceprofesseur_lien_externe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la page')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
            options={
                'verbose_name': 'Analytique de page',
                'verbose_name_plural': 'Analytiques de pages',
            },
        ),
    ]
