# Generated by Django 6.0.4 on 2026-06-12 20:56

import cloudinary_storage.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_pageanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='video_presentation',
            field=models.FileField(blank=True, help_text='Vidéo de présentation (Max 25 Mo, format 480p/720p recommandé)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='teachers/videos/', validators=[core.models.validate_video_size]),
        ),
    ]
