# Generated by Django 6.0.4 on 2026-06-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_teacherprofile_video_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='raison_incomplet',
            field=models.TextField(blank=True, help_text='Raison de la mise en attente (visible par le professeur)'),
        ),
    ]
