# Generated by Django 6.0.4 on 2026-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_teacherprofile_raison_incomplet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relance_incomplet_envoyee',
            field=models.BooleanField(default=False, help_text="Indique si l'email de relance pour profil incomplet a été envoyé"),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='statut_general',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'En cours'), ('EN_COURS', 'En cours'), ('FINALISE', 'Finalisé'), ('ESSAI_PROGRAMME', 'Essai programmé'), ('ESSAI_CONFIRME', 'Essai confirmé'), ('ESSAI_REALISE', 'Essai réalisé'), ('ENGAGEMENT_FINALISE', 'Engagement finalisé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='ESSAI_PROGRAMME', max_length=20),
        ),
    ]
