# Generated by Django 6.0.4 on 2026-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_profile_relance_incomplet_envoyee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='ville_quartier',
            field=models.CharField(help_text='Format Â« Quartier - Ville Â»', max_length=150),
        ),
        migrations.CreateModel(
            name='CustomChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'unique_together': {('category', 'value')},
            },
        ),
    ]
