# Generated by Django 6.0.4 on 2026-06-21 19:26

import json
import os
import unicodedata

from django.db import migrations
from django.conf import settings


def normalize(text):
    """Normalise un texte pour comparaison insensible à la casse et aux accents."""
    return unicodedata.normalize('NFKD', text.lower()).encode('ASCII', 'ignore').decode('utf-8')


def populate_matieres(apps, schema_editor):
    """
    Synchronise la table CustomChoice (category='matiere') avec le fichier matieres.json.
    - Ajoute les matières du JSON absentes de la base.
    - Ne supprime rien (les ajouts utilisateur personnalisés restent).
    """
    CustomChoice = apps.get_model('core', 'CustomChoice')

    # Charger le fichier JSON
    filepath = os.path.join(settings.BASE_DIR, 'core', 'matieres.json')
    with open(filepath, 'r', encoding='utf-8') as f:
        matieres_json = json.load(f)

    # Récupérer les matières déjà présentes en base (normalisées pour comparaison)
    existing = CustomChoice.objects.filter(category='matiere').values_list('value', flat=True)
    existing_normalized = {normalize(v): v for v in existing}

    # Insérer les nouvelles matières absentes
    to_create = []
    for matiere in matieres_json:
        norm = normalize(matiere)
        if norm not in existing_normalized:
            to_create.append(CustomChoice(category='matiere', value=matiere))
            existing_normalized[norm] = matiere  # éviter les doublons dans le lot

    if to_create:
        CustomChoice.objects.bulk_create(to_create, ignore_conflicts=True)


def reverse_populate(apps, schema_editor):
    """Reverse : ne rien faire (on ne supprime pas les données)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_teacherprofile_ville_quartier_customchoice'),
    ]

    operations = [
        migrations.RunPython(populate_matieres, reverse_populate),
    ]
