# Generated by Django 6.0.4 on 2026-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_populate_matieres_customchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='tarifs_par_classe',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionnaire associant un code de classe à son tarif (ex: {'6EME': 3000})"),
        ),
    ]
