# Generated by Django 6.0.4 on 2026-07-04 13:02

import core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_teacherprofile_tarifs_par_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classes_expertise',
            field=models.JSONField(blank=True, default=list, help_text="Top 3 classes (expertise) (ex: ['6EME','5EME'])", validators=[core.choices.validate_classes_expertise]),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='classe',
            field=models.CharField(blank=True, choices=[('MATERNELLE', 'Maternelle'), ('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE_LIT', '2nde Littéraire'), ('1ERE_LIT', '1ère Littéraire'), ('TLE_LIT', 'Tle Littéraire'), ('2NDE_SCI', '2nde Scientifique'), ('1ERE_SCI', '1ère Scientifique'), ('TLE_SCI', 'Tle Scientifique'), ('2NDE_TECH', '2nde Technique'), ('1ERE_TECH', '1ère Technique'), ('TLE_TECH', 'Tle Technique'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat'), ('ADULTE', 'Adultes / Professionnels'), ('CONCOURS', 'Préparation aux Concours')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='classe',
            field=models.CharField(blank=True, choices=[('MATERNELLE', 'Maternelle'), ('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE_LIT', '2nde Littéraire'), ('1ERE_LIT', '1ère Littéraire'), ('TLE_LIT', 'Tle Littéraire'), ('2NDE_SCI', '2nde Scientifique'), ('1ERE_SCI', '1ère Scientifique'), ('TLE_SCI', 'Tle Scientifique'), ('2NDE_TECH', '2nde Technique'), ('1ERE_TECH', '1ère Technique'), ('TLE_TECH', 'Tle Technique'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat'), ('ADULTE', 'Adultes / Professionnels'), ('CONCOURS', 'Préparation aux Concours')], max_length=30),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='classe',
            field=models.CharField(blank=True, choices=[('MATERNELLE', 'Maternelle'), ('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE_LIT', '2nde Littéraire'), ('1ERE_LIT', '1ère Littéraire'), ('TLE_LIT', 'Tle Littéraire'), ('2NDE_SCI', '2nde Scientifique'), ('1ERE_SCI', '1ère Scientifique'), ('TLE_SCI', 'Tle Scientifique'), ('2NDE_TECH', '2nde Technique'), ('1ERE_TECH', '1ère Technique'), ('TLE_TECH', 'Tle Technique'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat'), ('ADULTE', 'Adultes / Professionnels'), ('CONCOURS', 'Préparation aux Concours')], max_length=30),
        ),
    ]
