# Generated by Django 6.0.4 on 2026-07-04 13:03

from django.db import migrations

def migrate_classes_expertise(apps, schema_editor):
    TeacherProfile = apps.get_model('core', 'TeacherProfile')
    for profile in TeacherProfile.objects.all():
        if profile.classes_enseignees and isinstance(profile.classes_enseignees, list):
            # Prendre les 3 premières pour l'expertise
            profile.classes_expertise = profile.classes_enseignees[:3]
            # Le reste reste dans classes_enseignees (max 12 selon la nouvelle règle, mais on garde tout le reste existant pour éviter la perte de données)
            profile.classes_enseignees = profile.classes_enseignees[3:]
            profile.save(update_fields=['classes_expertise', 'classes_enseignees'])

def reverse_migrate_classes_expertise(apps, schema_editor):
    TeacherProfile = apps.get_model('core', 'TeacherProfile')
    for profile in TeacherProfile.objects.all():
        expertise = profile.classes_expertise if isinstance(profile.classes_expertise, list) else []
        enseignees = profile.classes_enseignees if isinstance(profile.classes_enseignees, list) else []
        profile.classes_enseignees = expertise + enseignees
        profile.classes_expertise = []
        profile.save(update_fields=['classes_expertise', 'classes_enseignees'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_teacherprofile_classes_expertise_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_classes_expertise, reverse_migrate_classes_expertise)
    ]
