# Generated by Django 6.0.4 on 2026-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_migrate_expertise_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(help_text='Contact laissé par le parent/élève', max_length=255, verbose_name='Email ou Téléphone')),
                ('matiere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matière recherchée')),
                ('localisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('resolved', models.BooleanField(default=False, verbose_name='Traitée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Alerte de recherche',
                'verbose_name_plural': 'Alertes de recherche',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='classe',
            field=models.CharField(blank=True, choices=[('MATERNELLE', 'MATERNELLE'), ('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde Littéraire', '2nde Littéraire'), ('1ère Littéraire', '1ère Littéraire'), ('Tle Littéraire', 'Tle Littéraire'), ('2nde Scientifique', '2nde Scientifique'), ('1ère Scientifique', '1ère Scientifique'), ('Tle Scientifique', 'Tle Scientifique'), ('2nde Technique', '2nde Technique'), ('1ère Technique', '1ère Technique'), ('Tle Technique', 'Tle Technique'), ('1ère année CAP', '1ère année CAP'), ('2ème année CAP', '2ème année CAP'), ('1ère année BEP', '1ère année BEP'), ('2ème année BEP', '2ème année BEP'), ('1ère année BAC Pro', '1ère année BAC Pro'), ('Tle BAC Pro', 'Tle BAC Pro'), ('1ère année BTS', '1ère année BTS'), ('2ème année BTS', '2ème année BTS'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Adultes / Professionnels', 'Adultes / Professionnels'), ('Préparation aux Concours', 'Préparation aux Concours')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='classe',
            field=models.CharField(blank=True, choices=[('MATERNELLE', 'MATERNELLE'), ('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde Littéraire', '2nde Littéraire'), ('1ère Littéraire', '1ère Littéraire'), ('Tle Littéraire', 'Tle Littéraire'), ('2nde Scientifique', '2nde Scientifique'), ('1ère Scientifique', '1ère Scientifique'), ('Tle Scientifique', 'Tle Scientifique'), ('2nde Technique', '2nde Technique'), ('1ère Technique', '1ère Technique'), ('Tle Technique', 'Tle Technique'), ('1ère année CAP', '1ère année CAP'), ('2ème année CAP', '2ème année CAP'), ('1ère année BEP', '1ère année BEP'), ('2ème année BEP', '2ème année BEP'), ('1ère année BAC Pro', '1ère année BAC Pro'), ('Tle BAC Pro', 'Tle BAC Pro'), ('1ère année BTS', '1ère année BTS'), ('2ème année BTS', '2ème année BTS'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Adultes / Professionnels', 'Adultes / Professionnels'), ('Préparation aux Concours', 'Préparation aux Concours')], max_length=30),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='classe',
            field=models.CharField(blank=True, choices=[('MATERNELLE', 'MATERNELLE'), ('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde Littéraire', '2nde Littéraire'), ('1ère Littéraire', '1ère Littéraire'), ('Tle Littéraire', 'Tle Littéraire'), ('2nde Scientifique', '2nde Scientifique'), ('1ère Scientifique', '1ère Scientifique'), ('Tle Scientifique', 'Tle Scientifique'), ('2nde Technique', '2nde Technique'), ('1ère Technique', '1ère Technique'), ('Tle Technique', 'Tle Technique'), ('1ère année CAP', '1ère année CAP'), ('2ème année CAP', '2ème année CAP'), ('1ère année BEP', '1ère année BEP'), ('2ème année BEP', '2ème année BEP'), ('1ère année BAC Pro', '1ère année BAC Pro'), ('Tle BAC Pro', 'Tle BAC Pro'), ('1ère année BTS', '1ère année BTS'), ('2ème année BTS', '2ème année BTS'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Adultes / Professionnels', 'Adultes / Professionnels'), ('Préparation aux Concours', 'Préparation aux Concours')], max_length=30),
        ),
    ]
