# Generated by Django 6.0.4 on 2026-07-20 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_searchalert_alter_apprenant_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='likes_methodologie',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de likes pour la méthodologie'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='likes_presentation',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de likes pour la présentation'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='total_favoris_historique',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de fois où ce prof a été ajouté aux favoris depuis le début'),
        ),
        migrations.CreateModel(
            name='ProfileReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('presentation', 'Présentation'), ('methodologie', 'Méthodologie')], max_length=20)),
                ('session_key', models.CharField(blank=True, help_text='Pour les visiteurs non connectés', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.teacherprofile')),
                ('user', models.ForeignKey(blank=True, help_text='Pour les utilisateurs connectés', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réaction de profil',
                'verbose_name_plural': 'Réactions de profil',
                'unique_together': {('professeur', 'section', 'session_key', 'user')},
            },
        ),
    ]
