# Generated by Django 6.0.4 on 2026-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_teacherprofile_likes_methodologie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube de la vidéo de présentation (ex: https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
