# Generated by Django 6.0.4 on 2026-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_youtube_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='youtube_video_url',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='ID YouTube de la vidéo de présentation (11 caractères, ex: dQw4w9WgXcQ)', max_length=11, null=True),
        ),
    ]
