# Generated by Django 6.0.4 on 2026-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_teacherprofile_youtube_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='classe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='quartier_ville',
            field=models.CharField(blank=True, help_text='Format Â« Quartier - Ville Â» pour matching', max_length=150),
        ),
    ]
