# Generated by Django 6.0.4 on 2026-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_teacherprofile_youtube_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='autorise_utilisation_video_promo',
            field=models.BooleanField(default=False, verbose_name="Autorise l'utilisation de la vidéo à des fins promotionnelles"),
        ),
    ]
