# Generated by Django 6.0.4 on 2026-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_teacherprofile_autorise_utilisation_video_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='popup_partage_vu',
            field=models.BooleanField(default=False, help_text="Indique si le prof a déjà vu le popup d'incitation au partage"),
        ),
    ]
