# Generated by Django 6.0.4 on 2026-08-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_teacherprofile_popup_partage_vu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='quartier_ville',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='quartier_ville',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='quartier_ville',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ville_quartier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ville', 'nom'],
                'unique_together': {('nom', 'ville')},
            },
        ),
        migrations.AddField(
            model_name='apprenant',
            name='quartier_ville_fk',
            field=models.ForeignKey(blank=True, help_text='Sélectionnez le quartier pour le matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to='core.quartier'),
        ),
        migrations.AddField(
            model_name='enfant',
            name='quartier_ville_fk',
            field=models.ForeignKey(blank=True, help_text='Sélectionnez le quartier pour le matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='core.quartier'),
        ),
        migrations.AddField(
            model_name='parent',
            name='quartier_ville_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='core.quartier'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='quartiers_couverts',
            field=models.ManyToManyField(related_name='professeurs', to='core.quartier'),
        ),
    ]
