# Generated by Django 6.0.4 on 2026-08-04 17:39

from django.db import migrations
import json
import os
from django.conf import settings

def parse_location(loc_string):
    if not loc_string:
        return None, None
    parts = loc_string.split(' - ')
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return loc_string.strip(), 'Inconnu'

def migrate_data(apps, schema_editor):
    Quartier = apps.get_model('core', 'Quartier')
    TeacherProfile = apps.get_model('core', 'TeacherProfile')
    Apprenant = apps.get_model('core', 'Apprenant')
    Parent = apps.get_model('core', 'Parent')
    Enfant = apps.get_model('core', 'Enfant')

    # 1. Prepopulate from localisations.json
    loc_file = os.path.join(settings.BASE_DIR, 'core', 'localisations.json')
    if os.path.exists(loc_file):
        with open(loc_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            for item in data:
                nom, ville = parse_location(item[0])
                if nom and ville:
                    Quartier.objects.get_or_create(nom=nom, ville=ville)

    def get_quartier(loc_string):
        nom, ville = parse_location(loc_string)
        if nom and ville:
            q, _ = Quartier.objects.get_or_create(nom=nom, ville=ville)
            return q
        return None

    # 2. Migrate TeacherProfile
    for teacher in TeacherProfile.objects.all():
        if teacher.ville_quartier:
            q = get_quartier(teacher.ville_quartier)
            if q:
                teacher.quartiers_couverts.add(q)
            
    # 3. Migrate Apprenant, Parent, Enfant
    for Model in [Apprenant, Parent, Enfant]:
        for instance in Model.objects.all():
            if instance.quartier_ville:
                q = get_quartier(instance.quartier_ville)
                if q:
                    instance.quartier_ville_fk = q
                    instance.save(update_fields=['quartier_ville_fk'])

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_apprenant_quartier_ville_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate),
    ]
