# Generated by Django 6.0.4 on 2026-08-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_migrate_quartiers_data'),
    ]

    operations = [
        # 1. Drop old ville_quartier CharField from TeacherProfile
        migrations.RemoveField(
            model_name='teacherprofile',
            name='ville_quartier',
        ),
        # 2. For Apprenant: drop old CharField, rename FK
        migrations.RemoveField(
            model_name='apprenant',
            name='quartier_ville',
        ),
        migrations.RenameField(
            model_name='apprenant',
            old_name='quartier_ville_fk',
            new_name='quartier_ville',
        ),
        # 3. For Enfant: drop old CharField, rename FK
        migrations.RemoveField(
            model_name='enfant',
            name='quartier_ville',
        ),
        migrations.RenameField(
            model_name='enfant',
            old_name='quartier_ville_fk',
            new_name='quartier_ville',
        ),
        # 4. For Parent: drop old CharField, rename FK
        migrations.RemoveField(
            model_name='parent',
            name='quartier_ville',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='quartier_ville_fk',
            new_name='quartier_ville',
        ),
    ]

