# Generated by Django 6.0.4 on 2026-09-09 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_apprenant_quartier_ville_fk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, help_text='Ex : Présentation générale, Méthodologie en Mathématiques', max_length=150, verbose_name='Titre de la vidéo')),
                ('youtube_url', models.URLField(help_text='Lien complet ou raccourci YouTube', verbose_name='URL de la vidéo YouTube')),
                ('youtube_video_id', models.CharField(max_length=20, verbose_name='Identifiant YouTube')),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validée'), ('REFUSE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de modération')),
                ('motif_refus_suggestions', models.TextField(blank=True, help_text="Transmis par email au professeur pour l'aider à peaufiner sa vidéo.", verbose_name="Suggestions d'amélioration / Motifs de refus")),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation / refus')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('autorise_utilisation_promo', models.BooleanField(default=False, verbose_name="Autorise l'utilisation à des fins promotionnelles")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.teacherprofile', verbose_name='Professeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_moderees', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par')),
            ],
            options={
                'verbose_name': 'Vidéo de professeur',
                'verbose_name_plural': 'Vidéos de professeurs',
                'ordering': ['ordre', '-date_validation', '-date_soumission'],
            },
        ),
    ]
