# Generated by Django 6.0.4 on 2026-09-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_teachervideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_teacher_video_submissions', models.BooleanField(default=True, help_text="Si décoché, le bouton d'accès sur le dashboard prof est désactivé et l'accès à la page de soumission est bloqué.", verbose_name='Autoriser les professeurs à ajouter/gérer leurs vidéos de présentation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
