# Generated by Django 6.0.4 on 2026-09-17 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_client_prospect', models.CharField(blank=True, help_text='Optionnel. Nom ou pseudo WhatsApp du parent (ex: M. Dossou).', max_length=150, null=True)),
                ('message_personnalisé', models.TextField(blank=True, help_text="Optionnel. Un petit mot d'introduction affiché en haut de la page.", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('professeurs', models.ManyToManyField(help_text='Sélectionnez les professeurs à présenter au parent.', related_name='selections', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'Sélection WhatsApp',
                'verbose_name_plural': 'Sélections WhatsApp',
            },
        ),
    ]
