# Generated by Django 6.0.2 on 2026-10-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_parentselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='a_vu_visite_guidee',
            field=models.BooleanField(default=False, help_text='A vu la visite guidée du dashboard'),
        ),
    ]
