# Generated by Django 6.0.2 on 2026-10-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_teacherprofile_a_vu_visite_guidee'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='date_dernier_calcul_score',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière actualisation du score', null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='score_fiabilite',
            field=models.PositiveBigIntegerField(default=0, help_text='Total des points cumulés de fiabilité'),
        ),
        migrations.CreateModel(
            name='OperationScoreFiabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('JOURNAL', 'Journal de séance'), ('REACTIVITE', 'Réactivité'), ('ENGAGEMENT_TERMINE', 'Engagement terminé'), ('AVIS', 'Avis familial'), ('CORRECTION', 'Correction manuelle')], max_length=50)),
                ('points', models.IntegerField(help_text='Nombre de points attribués')),
                ('reference_type', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('NEUTRALISE', 'Neutralisé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20)),
                ('operation_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operationscorefiabilite')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_fiabilite', to='core.teacherprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('professeur', 'type_operation', 'reference_type', 'reference_id'), name='unique_operation_fiabilite_per_source')],
            },
        ),
    ]
