# Generated by Django 6.0.4 on 2026-08-02 20:57

import django.db.models.deletion
import referrals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reward_amount', models.DecimalField(decimal_places=2, default=700, help_text='Montant de la prime en FCFA', max_digits=10)),
                ('enabled', models.BooleanField(default=True)),
                ('terms_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Programme Ambassadeur',
                'verbose_name_plural': 'Programme Ambassadeurs',
            },
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=referrals.models.generate_referral_code, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VISITED', 'Lien visité'), ('ACCOUNT_CREATED', 'Compte créé'), ('PROFILE_COMPLETED', 'Profil complété'), ('UNDER_REVIEW', 'En vérification'), ('VERIFIED', 'Vérifié'), ('REWARD_PENDING', 'Récompense en attente'), ('REWARD_PAID', 'Récompense payée'), ('REJECTED', 'Refusé')], default='VISITED', max_length=20)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reward_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reward_paid_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_processed', to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='referrals.referral')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Récompense',
                'verbose_name_plural': 'Récompenses',
            },
        ),
    ]
