"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-qsis4-wx7&s6c&6l0@arlw&44-dz7ow074to=@dzhxqysc!-7a')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Allowed hosts pour Render et développement local
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'profchezvousapp.com',
    'www.profchezvousapp.com',
    'pcv.onrender.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://profchezvousapp.com',
    'https://www.profchezvousapp.com',
]

# Ensure request.scheme is 'https' when behind Render proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'django.contrib.sitemaps',
    'core',
]

SITE_ID = 1

# Authentication configuration in the end of file

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
LOGIN_REDIRECT_URL = 'post_signup_redirect'
ACCOUNT_SIGNUP_FORM_CLASS = 'core.allauth_forms.CustomSignupForm'
SILENCED_SYSTEM_CHECKS = ['account.W001', 'account.W002']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- IL DOIT ÊTRE ICI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    #'core.middleware.ProfileCompletionMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_choices',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database - Configuration Render/PostgreSQL
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Priorité à la variable d'environnement DATABASE_URL (Render)
# Sinon fallback sur SQLite pour développement local
if os.getenv('DATABASE_URL'):
    DATABASES = {
        # Neon.tech : il est recommandé de garder conn_max_age à 0 pour éviter de maintenir 
        # des connexions inactives sur une base serverless / poolée.
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=0,
            conn_health_checks=True,
        )
    }
else:
    # SQLite pour développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Porto-Novo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'post_signup_redirect'
LOGOUT_REDIRECT_URL = 'home'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Fichiers uploadés par les utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration de sécurité pour la production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Pour que Allauth génère des URLs d'emails en HTTPS
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# Configuration Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Configuration des Stockages (Django 5.1+)
# default: Cloudinary pour les fichiers uploadés (Persistance sur Render)
# staticfiles: Django standard pour éviter les plantages collectstatic
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Paramètres de compatibilité pour les librairies tierces (Cloudinary, WhiteNoise)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# --- Configuration Business (Déploiement) ---
DEFAULT_ENGAGEMENT_PRICE = os.getenv('ENGAGEMENT_PRICE', '2000')
DEFAULT_CURRENCY = os.getenv('CURRENCY', 'FCFA')

# Paramètres de notation par défaut
RATING_DEFAULT_CERTIFIED = float(os.getenv('RATING_DEFAULT_CERTIFIED', '4.8'))
RATING_DEFAULT_STANDARD = float(os.getenv('RATING_DEFAULT_STANDARD', '4.5'))

# Seuils de prix pour la recherche
PRICE_THRESHOLDS = os.getenv('PRICE_THRESHOLDS', '2000,5000,10000').split(',')

# --- Badge "Suivi Rigoureux" ---
# Nombre minimum de bilans de séances pour obtenir le badge
SUIVI_RIGOUREUX_SEUIL_BILANS = int(os.getenv('SUIVI_RIGOUREUX_SEUIL_BILANS', '3'))
# Nombre de jours depuis le dernier bilan (si engagement actif)
SUIVI_RIGOUREUX_JOURS_RECENCE = int(os.getenv('SUIVI_RIGOUREUX_JOURS_RECENCE', '14'))

# Chemins des données
LOCALISATIONS_FILE = os.path.join(BASE_DIR, 'core', 'localisations.json')
MATIERES_FILE = os.path.join(BASE_DIR, 'core', 'matieres.json')

# Paramètres Premium
PREMIUM_MONTHLY_PRICE = os.getenv('PREMIUM_MONTHLY_PRICE', '5000')
PREMIUM_ENGAGEMENT_QUOTA = int(os.getenv('PREMIUM_ENGAGEMENT_QUOTA', '5'))

# --- Email Configuration (Brevo/SMTP) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))  # Timeout SMTP en secondes

# IMPORTANT : Cette adresse DOIT être vérifiée dans votre compte Brevo
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Prof Chez Vous <contact@profchezvousapp.com>')

# --- Logging (visible dans les logs Render) ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Bascule manuelle pour activer/d�sactiver l'upload de la vid�o de pr�sentation
VIDEO_UPLOAD_ENABLED = False
