# Generated by Django 6.0.4 on 2026-07-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description courte')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS de l'icône (ex: bi bi-person)", max_length=50, verbose_name='Icône')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('target_audience', models.CharField(choices=[('all', 'Tous'), ('parents', 'Parents & Apprenants'), ('teachers', 'Professeurs')], default='all', max_length=20, verbose_name='Public cible')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('keywords', models.CharField(blank=True, help_text='Mots-clés pour la recherche, séparés par des virgules', max_length=255, verbose_name='Mots-clés')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('related_articles', models.ManyToManyField(blank=True, to='help_center.article', verbose_name='Articles liés')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help_center.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
