# Generated by Django 6.0.2 on 2026-02-26 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vueprofil_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_message_date', models.DateTimeField(blank=True, null=True)),
                ('dernier_message_texte', models.TextField(blank=True)),
                ('statut_conversation', models.CharField(choices=[('DISCUSSION_LIBRE', 'Discussion libre'), ('NEGOCIATION', 'Engagement en négociation'), ('CONFIRME', 'Engagement confirmé'), ('TERMINE', 'Engagement terminé'), ('CLOSE', 'Conversation close')], default='DISCUSSION_LIBRE', max_length=30)),
                ('conversation_lue_par_parent', models.BooleanField(default=False)),
                ('conversation_lue_par_prof', models.BooleanField(default=False)),
                ('conversation_archivee', models.BooleanField(default=False)),
                ('dernier_message_auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dernier_messages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_parent', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='engagement_actif',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_active', to='core.engagement'),
        ),
    ]
