# Generated by Django 6.0.2 on 2026-02-27 09:48

import core.choices
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_evaluation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('TECHNIQUE', 'Technique'), ('SUPERIEUR', 'Supérieur'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(blank=True, max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom et prénom', max_length=200)),
                ('email_apprenant', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, help_text='Numéro WhatsApp', max_length=50)),
                ('photo_de_profil', models.ImageField(blank=True, null=True, upload_to='apprenants/photos/')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('niveau', models.CharField(blank=True, choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('TECHNIQUE', 'Technique'), ('SUPERIEUR', 'Supérieur'), ('AUTRE', 'Autre')], max_length=20)),
                ('classe', models.CharField(blank=True, choices=[('CI', 'CI'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Tle'), ('CAP1', '1ère année CAP'), ('CAP2', '2ème année CAP'), ('BEP1', '1ère année BEP'), ('BEP2', '2ème année BEP'), ('BACPRO1', '1ère année BAC Pro'), ('BACPRO_TLE', 'Tle BAC Pro'), ('BTS1', '1ère année BTS'), ('BTS2', '2ème année BTS'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('MASTER', 'Master'), ('PHD', 'Doctorat')], max_length=30)),
                ('matieres_recherchees', models.JSONField(blank=True, default=list, help_text='Matières prioritaires (max 5)', validators=[core.choices.validate_matieres_recherchees_max_5])),
                ('objectifs_motivations', models.JSONField(blank=True, default=list, help_text="Liste de codes ObjectifMotivation (ex: ['PREPARER_EXAMEN'])", validators=[core.choices.validate_objectifs_motivations])),
                ('description_difficultes', models.TextField(blank=True)),
                ('habitudes_de_travail', models.TextField(blank=True)),
                ('quartier_ville', models.CharField(blank=True, help_text='Format « Quartier-Ville » pour matching', max_length=150)),
                ('preference_de_cours', models.CharField(blank=True, choices=[('PARENT_HOME', 'Présentiel chez le parent'), ('APPRENANT_HOME', "Présentiel chez l'apprenant"), ('ONLINE', 'En ligne'), ('HYBRID', 'Hybride (presentiel + en ligne par visioconférence)')], max_length=30)),
                ('disponibilites', models.JSONField(blank=True, default=list, help_text="Liste de codes CreneauDisponibilite (ex: ['LUN_VEN_MATIN'])", validators=[core.choices.validate_creneaux_disponibilites])),
                ('abonnement_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenants', to='core.abonnement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
